# Numpy Introduction 

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# What is an array?

### An array is a fundamental data structure in computer programming and is used to store a collection of elements or values of the same data type in a contiguous block of memory. These elements are typically accessed using an index, which is an integer that represents the position of an element within the array.

In [3]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [4]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [5]:
a2 = a[ : , np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [6]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

# Creating Arrays with Numoy

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])

In [9]:
type(a) # type of array

numpy.ndarray

In [10]:
a.dtype # data type of array elements

dtype('int32')

In [11]:
type(b)

numpy.ndarray

In [12]:
b.dtype

dtype('int32')

In [13]:
a.shape


(7,)

In [14]:
print(b)

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


In [15]:

print(a)
a.shape


[1 2 3 4 5 6 7]


(7,)

In [16]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# Initiaze array

In [17]:
zeros = np.zeros((3, 4))  # (rows, columne)
zeros




array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
ones = np.ones((2, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
full = np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

# Creating an identity matrix

In [21]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array attributes

In [22]:
a.shape # for shape of array

(7,)

In [23]:
b.shape

(2, 7)

In [24]:
len(a) # give us the length elements in array

7

In [25]:
a.size # give us the numbers of elements in array


7

In [26]:
a.ndim # give us the dimension of array 

1

In [27]:
b.ndim

2

In [28]:
identity.ndim

2

# Basic operations

In [29]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [31]:
g = a-b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [32]:
g = b-a
g

array([[0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3]])

In [33]:
h = a+b # addition
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [34]:
# another method
h1 = np.add(a, b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [35]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [36]:
# division
j = a/b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [37]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
# square of each element
k = a**2
k

array([ 1,  4,  9, 16, 25, 36, 49])