# Numpy (Part-2)

In [1]:
import numpy as np

In [2]:
empty = np.empty((2, 4))
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
empty = np.empty((3, 4))
print(empty)

[[ 1.40517611e-309 -4.25733348e-167  2.81143436e+180  5.79460940e-318]
 [ 0.00000000e+000  1.28567829e-300  1.39067116e-309 -1.59570309e-234]
 [ 3.27165330e-319 -1.37059235e-080  3.79755650e-313  0.00000000e+000]]


In [4]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [5]:
even = np.arange(0, 23, 2) # array of even numbers from 0 to 23
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [6]:
# array of odd numbers from 0 to 23
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [7]:
# specific differnce between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [8]:
lin = np.linspace(0, 20, num=10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
lin.dtype

dtype('float64')

In [10]:
# define the dtype of array
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [11]:
# define the dtype of array
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

In [12]:
# define the dtype of array
x = np.arange(2, dtype=np.float64)
x

array([0., 1.])

In [13]:
# define the dtype of array
x = np.arange(22.6, dtype=np.float64)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])

In [14]:
# define the dtype of array
x = np.arange(0 ,22.6, 1.5, dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [15]:
# sorting an array
arr = np.array([2, 1, 3, 5, 4, 7, 8 ])
arr

array([2, 1, 3, 5, 4, 7, 8])

In [16]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 7, 8])

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [18]:
# concatenate these array
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D Array

In [19]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6]]) # 1x2 array


In [20]:
x

array([[1, 2],
       [3, 4]])

In [21]:
y

array([[5, 6]])

In [23]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
w = np.array([[5,1], [7,1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array

In [27]:
z1 = np.concatenate((w,x), axis=1) 
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [28]:
x.ndim

2

In [29]:
# creat a 3D array 
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [30]:
array_example.ndim

3

In [31]:
len(array_example)

3

In [32]:
array_example.size

24

In [33]:
array_example.dtype

dtype('int32')

In [34]:
array_example.shape

(3, 2, 4)

In [39]:
# creat a 3D array of size (3,1,4)
a1=np.array([[[0,1,2,3,]],[[4,5,6,7,]],[[0,1,2,3]]])
a1.ndim

3

In [36]:
a.shape

(3, 1, 4)

In [40]:
# reshape the a 

a2=a1.reshape(6,2)
a2.shape

(6, 2)

In [41]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [42]:
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [43]:
# creat a 1D array
a=np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [48]:
# convert that in to 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [46]:
c= a[: , np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Indexing and slicing

In [49]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a[2]

3

In [51]:
a[2:5]

array([3, 4, 5])

In [52]:
a[-4:-2]

array([5, 6])

In [53]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [54]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
b[b<5]


array([1, 2, 3, 4])

In [56]:
b[b<2]

array([1])

In [57]:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
b[b>10]

array([11, 12])

In [59]:
b[b>=10]

array([10, 11, 12])

In [60]:
b[b<=10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
b[b % 2==0] # filter even number

array([ 2,  4,  6,  8, 10, 12])

In [62]:
# filter odd number
b[b % 2== 1]

array([ 1,  3,  5,  7,  9, 11])

In [65]:
# use two conditions
b[(b>2) & (b<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# use three condition and filter the arrays
b[(b>2) & (b<11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [69]:
b[(b>2) | (b<11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])