# Numpy Indexing and Slicing

In [1]:
import numpy as np

In [2]:
# creat an array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[0:1]

array([1])

In [4]:
a[-1]

7

In [5]:
a[-2]

6

In [7]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [8]:
b[2]

4

In [10]:
c=b.reshape(2, 3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [11]:
c[0]

array([0, 2, 4])

In [13]:
c=b.reshape(3, 2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [14]:
c[1]

array([4, 6])

In [16]:
c[0]

array([0, 2])

In [15]:
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [17]:
c[(c<5) | (c>7)]

array([ 0,  2,  4,  8, 10])

## Enlist boolean operators conditional operators

------

# Making an array from a data or another array




In [18]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [19]:
len(a)

45

In [20]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [21]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [22]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])